// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Fs from "fs";
import * as Person from "./Person.js";

var json = Fs.readFileSync("src/Ex3Record/person1.json", "utf8");

console.log(json);

var p = Person.fromJson(json);

if (p.TAG) {
  console.log(p._0.message);
} else {
  console.log(p._0);
}

export {
  json ,
  p ,
  
}
/* json Not a pure module */
