// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Js_exn from "bs-platform/lib/es6/js_exn.js";
import * as ResultError from "../Ex0/ResultError.js";
import * as PersonExtJs from "./PersonExt.js";
import * as Caml_js_exceptions from "bs-platform/lib/es6/caml_js_exceptions.js";

function parseJsonExt(prim) {
  return PersonExtJs.parseJsonExt(prim);
}

function fromJson(json) {
  try {
    var record = PersonExtJs.parseJsonExt(json);
    return {
            TAG: /* Ok */0,
            _0: record
          };
  }
  catch (raw_e){
    var e = Caml_js_exceptions.internalToOCamlException(raw_e);
    if (e.RE_EXN_ID === Js_exn.$$Error) {
      return {
              TAG: /* Error */1,
              _0: ResultError.fromJsExn(e._1)
            };
    }
    throw e;
  }
}

export {
  parseJsonExt ,
  fromJson ,
  
}
/* ./PersonExt.js Not a pure module */
