// Generated by ReScript, PLEASE EDIT WITH CARE


function fromJsExn(exn) {
  var s = exn.message;
  var message = s !== undefined ? s : "NO_MESSAGE";
  var s$1 = exn.stack;
  var stack = s$1 !== undefined ? s$1 : "NO_STACK";
  return {
          message: message,
          stack: stack
        };
}

export {
  fromJsExn ,
  
}
/* No side effect */
