// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Fs from "../Ex4Module/Fs.js";
import * as Pr from "./Pr.js";
import * as Js_exn from "bs-platform/lib/es6/js_exn.js";
import * as Person from "../Ex3Record/Person.js";
import * as Caml_exceptions from "bs-platform/lib/es6/caml_exceptions.js";

console.log("Ex5Main");

var StringLengthError = Caml_exceptions.create("Ex5Main.StringLengthError");

function btos(b) {
  if (b) {
    return "true";
  } else {
    return "false";
  }
}

Pr.$$catch(Pr.$$then(Pr.$$then(Pr.$$then(Fs.readFileAsync("src/Ex3Record/person1.json"), (function (s1, param) {
                    var s = "{\"age\": 33, \"alive\": true}";
                    console.log("s=", s);
                    var person = Person.fromJson(s);
                    if (!person.TAG) {
                      return person._0;
                    }
                    throw Js_exn.raiseError(person._0.message);
                  })), (function (r, param) {
                console.log("r=", r);
                var len = "hello1".length;
                if (len === 5) {
                  throw {
                        RE_EXN_ID: StringLengthError,
                        _1: "str length is 6",
                        Error: new Error()
                      };
                }
                return len;
              })), (function (i, param) {
            console.log("i=", i);
            return true;
          })), (function (e) {
        console.log(e);
        
      }));

export {
  StringLengthError ,
  btos ,
  
}
/*  Not a pure module */
