// Generated by ReScript, PLEASE EDIT WITH CARE

import * as PrExtJs from "./PrExt.js";

function $$catch(prim, prim$1) {
  PrExtJs.catchErrorExt(prim, prim$1);
  
}

function $$then(prim, prim$1) {
  return PrExtJs.thenResultExt(prim, prim$1);
}

export {
  $$catch ,
  $$then ,
  
}
/* ./PrExt.js Not a pure module */
