// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_HashMapString from "bs-platform/lib/es6/belt_HashMapString.js";

var hm = Belt_HashMapString.make(10);

console.log("isEmpty=", Belt_HashMapString.isEmpty(hm));

Belt_HashMapString.set(hm, "one", 1);

console.log("isEmpty=", Belt_HashMapString.isEmpty(hm));

console.log("has(\"one\")=", Belt_HashMapString.has(hm, "one"));

Belt_HashMapString.set(hm, "two", 2);

console.log("toArray()=", Belt_HashMapString.toArray(hm));

var three = Belt_HashMapString.get(hm, "three");

if (three !== undefined) {
  console.log("three=", three);
} else {
  console.log("no key \"three\"");
}

var two = Belt_HashMapString.get(hm, "two");

if (two !== undefined) {
  console.log("two=", two);
} else {
  console.log("no key \"two\"");
}

var HashMap;

export {
  HashMap ,
  hm ,
  three ,
  two ,
  
}
/* hm Not a pure module */
