// Generated by ReScript, PLEASE EDIT WITH CARE


var greeting = "greetings!";

console.log(greeting);

var message = "hello world!";

console.log(message);

var result = 1;

var result$1 = "something " + String(result);

console.log("result=" + result$1);

function getNumber(param) {
  return 7;
}

var PrivateLet = {
  b: 4,
  getNumber: getNumber
};

export {
  greeting ,
  message ,
  result$1 as result,
  PrivateLet ,
  
}
/*  Not a pure module */
