// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Fs from "./Fs.js";

var fileName = "README.md";

console.log("exists=" + (
      Fs.exists(fileName) ? "true" : "false"
    ));

var contents = Fs.readFile(fileName);

if (contents.TAG) {
  var error = contents._0;
  console.log(error.message, error.stack);
} else {
  console.log("contents...\n" + contents._0);
}

export {
  fileName ,
  
}
/*  Not a pure module */
