// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Js_exn from "bs-platform/lib/es6/js_exn.js";
import * as FsExtJs from "./FsExt.js";
import * as ResultError from "../Ex0/ResultError.js";
import * as Caml_js_exceptions from "bs-platform/lib/es6/caml_js_exceptions.js";

function readFileExt(prim) {
  return FsExtJs.readFileExt(prim);
}

function readFileAsync(prim) {
  return FsExtJs.readFileAsyncExt(prim);
}

function exists(prim) {
  return FsExtJs.existsExt(prim);
}

function readFile(path) {
  try {
    var s = FsExtJs.readFileExt(path);
    return {
            TAG: /* Ok */0,
            _0: s
          };
  }
  catch (raw_e){
    var e = Caml_js_exceptions.internalToOCamlException(raw_e);
    if (e.RE_EXN_ID === Js_exn.$$Error) {
      return {
              TAG: /* Error */1,
              _0: ResultError.fromJsExn(e._1)
            };
    }
    throw e;
  }
}

export {
  readFileExt ,
  readFileAsync ,
  exists ,
  readFile ,
  
}
/* ./FsExt.js Not a pure module */
