// Generated by ReScript, PLEASE EDIT WITH CARE

import * as ParseJs from "./Parse.js";

function toPerson(prim) {
  return ParseJs.toPerson(prim);
}

export { toPerson };
/* ./Parse.js Not a pure module */
