// Generated by ReScript, PLEASE EDIT WITH CARE


var greeting = "greetings!";

console.log(greeting);

var message = "hello world!";

console.log(message);

function getNumber(param) {
  return 7;
}

var PrivateLet = {
  b: 4,
  getNumber: getNumber
};

var result = "something";

export {
  greeting ,
  message ,
  result ,
  PrivateLet ,
  
}
/*  Not a pure module */
