// Generated by ReScript, PLEASE EDIT WITH CARE


var greeting = "hello!";

var response = greeting === "greetings!" ? "greetings back at you!" : "hey.";

console.log(response);

export {
  greeting ,
  response ,
  
}
/* response Not a pure module */
